"""Sequence-to-circuit and simulation utilities.

CUDA-Q is the paper-fidelity target backend. The MVP also contains a determinant-space
state-vector simulator over the H4 CASCI basis so tests and local smoke runs can execute
on machines without CUDA-Q. The public API is backend-oriented, making replacement with a
full CUDA-Q fermionic-excitation decomposition straightforward.
"""

from __future__ import annotations

from dataclasses import dataclass
import numpy as np

from .chemistry import DeterminantBasis
from .operator_pool import ExcitationOperator, OperatorPool, approximate_gate_count


@dataclass(frozen=True)
class CircuitSampleResult:
    counts: dict[str, int]
    probabilities: dict[str, float]
    gate_count: dict[str, int]
    backend: str


@dataclass(frozen=True)
class CudaQCircuitSource:
    """Serializable CUDA-Q kernel source for inspecting/generated-circuit handoff."""

    source: str
    gate_count: dict[str, int]


def hf_state_vector(basis: DeterminantBasis) -> np.ndarray:
    state = np.zeros(basis.size, dtype=np.complex128)
    state[basis.index_by_bitstring[basis.hf_bitstring]] = 1.0
    return state


def _apply_annihilate(occ: int, orbital: int) -> tuple[int, int] | None:
    if ((occ >> orbital) & 1) == 0:
        return None
    parity = (occ & ((1 << orbital) - 1)).bit_count()
    return occ ^ (1 << orbital), -1 if parity % 2 else 1


def _apply_create(occ: int, orbital: int) -> tuple[int, int] | None:
    if ((occ >> orbital) & 1) == 1:
        return None
    parity = (occ & ((1 << orbital) - 1)).bit_count()
    return occ | (1 << orbital), -1 if parity % 2 else 1


def apply_excitation_to_occ(
    occ: int,
    annihilate: tuple[int, ...],
    create: tuple[int, ...],
) -> tuple[int, int] | None:
    """Apply product of creators/annihilators to a spin-orbital occupation integer.

    Operators are applied right-to-left: annihilate occupied orbitals, then create
    virtual orbitals. Returns the new occupation and fermionic sign.
    """
    sign = 1
    cur = occ
    for orbital in annihilate:
        out = _apply_annihilate(cur, orbital)
        if out is None:
            return None
        cur, s = out
        sign *= s
    for orbital in reversed(create):
        out = _apply_create(cur, orbital)
        if out is None:
            return None
        cur, s = out
        sign *= s
    return cur, sign


def _bitstring_to_occ_int(bitstring: str) -> int:
    return sum((ch == "1") << i for i, ch in enumerate(bitstring))


def _occ_int_to_bitstring(occ: int, n_qubits: int) -> str:
    return "".join("1" if ((occ >> i) & 1) else "0" for i in range(n_qubits))


def apply_excitation_rotation(
    state: np.ndarray,
    op: ExcitationOperator,
    basis: DeterminantBasis,
) -> np.ndarray:
    """Apply exp(theta * (T - T^dagger)) in the determinant basis."""
    if op.is_noop:
        return state.copy()

    out = state.copy()
    visited: set[tuple[int, int]] = set()
    c = np.cos(op.angle)
    s = np.sin(op.angle)

    for idx, bitstring in enumerate(basis.bitstrings):
        occ = _bitstring_to_occ_int(bitstring)
        partner = apply_excitation_to_occ(occ, op.annihilate, op.create)
        if partner is None:
            continue
        partner_occ, sign = partner
        partner_bitstring = _occ_int_to_bitstring(partner_occ, basis.n_qubits)
        jdx = basis.index_by_bitstring.get(partner_bitstring)
        if jdx is None:
            continue
        key = tuple(sorted((idx, jdx)))
        if key in visited:
            continue
        visited.add(key)

        a = state[idx]
        b = state[jdx]
        out[idx] = c * a - sign * s * b
        out[jdx] = sign * s * a + c * b
    return out


def simulate_state_vector(
    sequence: list[int] | np.ndarray,
    pool: OperatorPool,
    basis: DeterminantBasis,
) -> np.ndarray:
    state = hf_state_vector(basis)
    for token in sequence:
        state = apply_excitation_rotation(state, pool[int(token)], basis)
    norm = np.linalg.norm(state)
    if norm == 0:
        raise FloatingPointError("zero state generated by excitation sequence")
    return state / norm


def sample_counts_from_state(
    state: np.ndarray,
    basis: DeterminantBasis,
    shots: int,
    rng: np.random.Generator,
) -> tuple[dict[str, int], dict[str, float]]:
    probs = np.abs(state) ** 2
    probs = probs / probs.sum()
    sampled = rng.multinomial(int(shots), probs)
    counts = {
        basis.bitstrings[i]: int(c)
        for i, c in enumerate(sampled)
        if int(c) > 0
    }
    probabilities = {basis.bitstrings[i]: float(p) for i, p in enumerate(probs) if p > 1e-15}
    return counts, probabilities


def sequence_to_cudaq_source(
    sequence: list[int] | np.ndarray,
    pool: OperatorPool,
    basis: DeterminantBasis,
) -> CudaQCircuitSource:
    """Convert an operator sequence into a CUDA-Q Python kernel source string.

    The MVP source is meant for paper-fidelity integration/inspection. It initializes
    the HF determinant and emits a compact gate block per discrete excitation token. The
    determinant-space simulator remains the scientifically validated active-space path in
    this repository; replacing these approximate blocks with a backend-specific exact
    fermionic-excitation decomposition is the next CUDA-Q production step.
    """
    lines = [
        "import cudaq",
        "",
        "@cudaq.kernel",
        "def h4_sequence_kernel():",
        f"    q = cudaq.qvector({basis.n_qubits})",
    ]
    hf_occ = [i for i, bit in enumerate(basis.hf_bitstring) if bit == "1"]
    for qubit in hf_occ:
        lines.append(f"    x(q[{qubit}])")
    for token in sequence:
        op = pool[int(token)]
        if op.is_noop:
            continue
        involved = list(op.annihilate + op.create)
        if op.rank == 1:
            src, dst = op.annihilate[0], op.create[0]
            lines.extend(
                [
                    f"    # {op.name}",
                    f"    cx(q[{src}], q[{dst}])",
                    f"    ry({2 * op.angle:.17g}, q[{dst}])",
                    f"    cx(q[{src}], q[{dst}])",
                ]
            )
        else:
            target = involved[-1]
            controls = involved[:-1]
            lines.append(f"    # {op.name}")
            for q in controls:
                lines.append(f"    cx(q[{q}], q[{target}])")
            lines.append(f"    rz({2 * op.angle:.17g}, q[{target}])")
            for q in reversed(controls):
                lines.append(f"    cx(q[{q}], q[{target}])")
    lines.append("    mz(q)")
    return CudaQCircuitSource("\n".join(lines) + "\n", approximate_gate_count(sequence, pool))


def sample_sequence_circuit(
    sequence: list[int] | np.ndarray,
    pool: OperatorPool,
    basis: DeterminantBasis,
    shots: int,
    rng: np.random.Generator,
    backend: str = "determinant",
    cudaq_target: str | None = None,
    cudaq_option: str | None = None,
    cudaq_seed: int | None = None,
    cudaq_reverse_bitstrings: bool = False,
) -> CircuitSampleResult:
    """Sample measurement counts for a generated operator sequence."""
    if backend == "cudaq":
        return _sample_with_cudaq_or_raise(
            sequence,
            pool,
            basis,
            shots,
            rng,
            target=cudaq_target,
            option=cudaq_option,
            seed=cudaq_seed,
            reverse_bitstrings=cudaq_reverse_bitstrings,
        )
    if backend != "determinant":
        raise ValueError(f"unknown backend {backend!r}; expected determinant or cudaq")
    state = simulate_state_vector(sequence, pool, basis)
    counts, probabilities = sample_counts_from_state(state, basis, shots, rng)
    return CircuitSampleResult(
        counts=counts,
        probabilities=probabilities,
        gate_count=approximate_gate_count(sequence, pool),
        backend="determinant",
    )


def _sample_with_cudaq_or_raise(
    sequence: list[int] | np.ndarray,
    pool: OperatorPool,
    basis: DeterminantBasis,
    shots: int,
    rng: np.random.Generator,
    target: str | None = None,
    option: str | None = None,
    seed: int | None = None,
    reverse_bitstrings: bool = False,
) -> CircuitSampleResult:
    """Sample a generated sequence with a real CUDA-Q kernel backend."""
    from .cudaq_backend import sample_cudaq_sequence

    del rng  # CUDA-Q owns backend sampling randomness once its seed is configured.
    result = sample_cudaq_sequence(
        sequence,
        pool,
        basis,
        shots=shots,
        target=target,
        option=option,
        seed=seed,
        reverse_bitstrings=reverse_bitstrings,
    )
    return CircuitSampleResult(
        counts=result.counts,
        probabilities=result.probabilities,
        gate_count=result.resources,
        backend="cudaq",
    )
